### PR TITLE
2020-06-06 data

### PR DESCRIPTION
**Pull request by zarifmahmud**
Have updated data for covid

### CODE REVIEW

**Comment by rrwen** [comment]
Hi @zarifmahmud Could you provide some details to the changes from our original covid model data? 

There is also another pull request at #9 - is this one still valid?

Let me know thanks!

**Comment by zarifmahmud** [comment]
Hey Richard,
These are basically just more updated data for the website, based on input data that was collected on the day of the commit message. Right now I'm running an automated script that is meant to pull the most recent version of the data producing code, and then run the models and push the data here.

I don't think there are changes to the columns in the covid19_model_prediction.csv file apart from an addition of a "continent" column. There's also another file, covid19_model_predictions_per_million that gets rid of the cases columns, and normalizes the data for per million.

**Comment by rrwen** [comment]
@zarifmahmud Thanks Zarif - so should we get rid of #9 ?

Also, do you know if the millions data is needed (does matthew's visualization load faster on the website)?

**Comment by zarifmahmud** [comment]
@rrwen Yep, #9 could be removed.

And the perMillions files were meant so that the CSV files would load faster, so we got rid of a lot of extra rows, and moved US states to another CSV file. @eborgnine could confirm the final plans though.

Also it looks like yesterday's data didn't have the US Aggregated data in it, so I fixed a problem with that and today's file has that data. Also, I added the covid19_per_million_usa.csv file which contains per million data for US states. This was also put separately so that we could have different visualizations for the countries in the per_million file and the US states.

**Comment by zarifmahmud** [comment]
@rrwen Would it be okay to merge this pull request?

**Review by rrwen — CHANGES_REQUESTED** [review]
@zarifmahmud Thanks for the info!

Before I merge this into `master`, please:

1. Put the two millions csv files into their own folders under 📁 `data`:
    ```
    📁 data/
    | --- 📁 covid_model_predictions_per_million/
            | --- 📄 covid19_model_predictions_per_million.csv
    | --- 📁 covid_model_predictions_per_million_usa/
            | --- 📄 covid19_model_predictions_per_million_usa.csv
    ```
2. Create data dictionaries  (example [here](https://github.com/cghr-toronto/covid-data/blob/master/data/covid19_model_predictions/covid19_model_predictions_dictionary.csv)):
    ```
    📁 data/
    | --- 📁 covid_model_predictions_per_million/
            | --- 📄 covid19_model_predictions_per_million.csv
            | --- 📄 covid19_model_predictions_per_million_dictionary.csv
    | --- 📁 covid_model_predictions_per_million_usa/
            | --- 📄 covid19_model_predictions_per_million_usa.csv
            | --- 📄 covid19_model_predictions_per_million_usa_dictionary.csv
    ```
3. Create a short 📖 `README.md` file describing the contents (see [here](https://github.com/cghr-toronto/covid-data/blob/master/CONTRIBUTING.md#dataset-folders)):
    ```
    📁 data/
    | --- 📁 covid_model_predictions_per_million/
            | --- 📄 covid19_model_predictions_per_million.csv
            | --- 📄 covid19_model_predictions_per_million_dictionary.csv
            | --- 📖 README.md
    | --- 📁 covid_model_predictions_per_million_usa/
            | --- 📄 covid19_model_predictions_per_million_usa.csv
            | --- 📄 covid19_model_predictions_per_million_usa_dictionary.csv
            | --- 📖 README.md
    ```

Any further additional datasets follow the same pattern and standards outlined [here](https://github.com/cghr-toronto/covid-data/blob/master/CONTRIBUTING.md#data-submission-standards).

Once these are merged into master, they will also be available automatically at:

:link: https://covid.cghr.dev/data

**Comment by zarifmahmud** [comment]
Hi Richard, sorry for the delay, I ran into some trouble with getting up to date data from the model. That's been fixed, and I've added in the data dictionaries and README files for each of the folders.

**Review by rrwen — APPROVED** [review]
@zarifmahmud Thanks Zarif and no worries about the delay! I am merging these into master 👍

**Pull request merged**
